# Generated by Django 3.2 on 2022-08-15 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenances', '0002_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromise',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
        migrations.AlterField(
            model_name='compromise',
            name='year',
            field=models.SmallIntegerField(editable=False, verbose_name='Año'),
        ),
        migrations.AlterUniqueTogether(
            name='compromise',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='compromise',
            name='user',
        ),
    ]
