# Generated by Django 3.2 on 2022-08-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0003_auto_20220815_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromise',
            name='total_computers',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Computadoras Totales'),
        ),
    ]
