# Generated by Django 3.2 on 2022-08-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0004_alter_compromise_total_computers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromise',
            name='estimated_computers',
            field=models.PositiveSmallIntegerField(verbose_name='Computadoras Estimadas'),
        ),
    ]
