# Generated by Django 3.2 on 2022-08-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0005_alter_compromise_estimated_computers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromise',
            name='estimated_computers',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Computadoras Estimadas'),
        ),
    ]
