# Generated by Django 3.2 on 2022-08-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('code', 'name')},
        ),
    ]
