# Generated by Django 3.2 on 2022-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicaldepartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldepartment',
            name='code',
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='id',
            field=models.CharField(db_index=True, max_length=2, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
    ]
