# Generated by Django 3.2 on 2022-08-14 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('owner', models.CharField(choices=[('MP', 'MP'), ('AECI/MP', 'AECI/MP'), ('BANTRAB/MP', 'BANTRAB/MP'), ('BID/MP', 'BID/MP'), ('CAFCA/MP+', 'CAFCA/MP+'), ('CAFCA/MP', 'CAFCA/MP'), ('CICAM/MP', 'CICAM/MP'), ('CICIG/MP', 'CICIG/MP'), ('DCH/MP', 'DCH/MP'), ('EA/MP', 'EA/MP'), ('COREA/MP', 'COREA/MP'), ('GEMPCE', 'GEMPCE'), ('EGMPCE', 'EGMPCE'), ('UNICEF/MP', 'UNICEF/MP'), ('UNFPA/MP', 'UNFPA/MP'), ('FPCP/MP', 'FPCP/MP'), ('FGSC/MP', 'FGSC/MP'), ('GC/MP', 'GC/MP'), ('LED/MP', 'LED/MP'), ('MIJ/MP', 'MIJ/MP'), ('MP/OIM', 'MP/OIM'), ('OADHAG/MP', 'OADHAG/MP'), ('UNODC/MP', 'UNODC/MP'), ('OIM/MP', 'OIM/MP'), ('USAID/MP', 'USAID/MP'), ('PARJ/MP', 'PARJ/MP'), ('SEJUST/MP', 'SEJUST/MP'), ('USAIDMP', 'USAIDMP'), ('AECIMP', 'AECIMP'), ('PNUDMP', 'PNUDMP'), ('PNUD/MP', 'PNUD/MP'), ('PJES/MP', 'PJES/MP'), ('LEDNASMP', 'LEDNASMP'), ('USA ID/MP', 'USA ID/MP'), ('PAVI/MP', 'PAVI/MP'), ('PJCVI/MP', ''), ('NAS', 'NAS'), ('NAS/MP', 'NAS/MP'), ('SEICMSJ/AECID', 'SEICMSJ/AECID'), ('SEICMSJ/MP', 'SEICMSJ/MP'), ('SENABED/MP', 'SENABED/MP'), ('STU/MP', 'STU/MP'), ('SICA/MP', 'SICA/MP'), ('MINISTERIO PUBLICO', 'MINISTERIO PUBLICO')], default='MP', max_length=50, verbose_name='Propietario')),
                ('year', models.CharField(max_length=4, verbose_name='Año')),
                ('code', models.CharField(max_length=8, verbose_name='Codigo')),
                ('correlative', models.CharField(max_length=6, verbose_name='Correlativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee', verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
