# Generated by Django 3.2 on 2022-08-13 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
                ('estimated_computers', models.PositiveSmallIntegerField(default=0, verbose_name='Estimated Computers')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Ubication',
                'verbose_name_plural': 'Ubications',
            },
        ),
    ]
