# Generated by Django 3.2 on 2022-08-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubication',
            options={'verbose_name': 'Fiscalía', 'verbose_name_plural': 'Fiscalías'},
        ),
    ]
