# Generated by Django 3.2 on 2022-08-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubications', '0002_alter_ubication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubication',
            name='code',
            field=models.CharField(default=1, max_length=6, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
